# Generated by Django 4.1.6 on 2023-02-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('pages', models.PositiveIntegerField(default=4)),
                ('price', models.FloatField(default=0.0)),
                ('type_cover', models.CharField(choices=[('Твёрдый', 'Твёрдый'), ('Мягкий', 'Мягкий'), ('Интегральный', 'Интегральный'), ('Картонный', 'Картонный')], max_length=18)),
                ('size', models.CharField(choices=[('A4', '210 х 297'), ('A5', '145 x 205'), ('A6', '102 х 142'), ('A7', '74 х 105')], max_length=2)),
                ('date_public', models.DateField(default='2000-12-09')),
                ('exist', models.BooleanField(default=True)),
            ],
        ),
    ]
