# Generated by Django 4.1.6 on 2023-02-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_public',
            field=models.DateField(auto_now_add=True),
        ),
    ]
