# Generated by Django 4.1.6 on 2023-02-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0002_alter_book_date_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=30, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=60, verbose_name='название'),
        ),
    ]
