# Generated by Django 4.1.6 on 2023-03-03 18:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0003_alter_book_author_alter_book_price_alter_book_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=30, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_public',
            field=models.DateField(default=datetime.date(2023, 3, 3), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='exist',
            field=models.BooleanField(default=True, verbose_name='В наличии?'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(default=4, verbose_name='Страниц'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='book',
            name='size',
            field=models.CharField(choices=[('A4', '210 х 297'), ('A5', '145 x 205'), ('A6', '102 х 142'), ('A7', '74 х 105')], max_length=2, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='book',
            name='type_cover',
            field=models.CharField(choices=[('Твёрдый', 'Твёрдый'), ('Мягкий', 'Мягкий'), ('Интегральный', 'Интегральный'), ('Картонный', 'Картонный')], max_length=18, verbose_name='Тип обложки'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=60)),
                ('nickname', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.book')),
            ],
        ),
    ]
