# Generated by Django 4.1.6 on 2023-03-18 18:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0004_alter_book_options_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, height_field=100, upload_to='image/', width_field=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='date_add',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_public',
            field=models.DateField(default=datetime.date(2023, 3, 18), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.CharField(max_length=30, verbose_name='Ник'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='theme',
            field=models.CharField(help_text='Тема, проблема', max_length=60, verbose_name='Тема'),
        ),
    ]
