# Generated by Django 4.1.6 on 2023-03-26 07:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mylibrary', '0005_book_picture_comment_date_add_comment_date_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Сказки', 'Сказки'), ('Сборники', 'Сборники'), ('Классика', 'Классика'), ('Научно-популярные', 'Научно-Популярные'), ('Справочники', 'Справочники'), ('Другое', 'Другое')], max_length=80, verbose_name='Наименование категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date_add',
        ),
        migrations.AlterField(
            model_name='book',
            name='date_public',
            field=models.DateField(default=datetime.date(2023, 3, 26), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, upload_to='image/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('Передано', 'Передано'), ('Ожидает', 'Ожидает'), ('Собирается', 'Собирается')], default='Собирается', max_length=80, verbose_name='Статус')),
                ('books', models.ManyToManyField(related_name='+', to='mylibrary.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mylibrary.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
