# Generated by Django 4.1.6 on 2023-03-26 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0006_category_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=30, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mylibrary.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='type_cover',
            field=models.CharField(blank=True, choices=[('Твёрдый', 'Твёрдый'), ('Мягкий', 'Мягкий'), ('Интегральный', 'Интегральный'), ('Картонный', 'Картонный')], max_length=18, verbose_name='Тип обложки'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
